import React, { useState, useRef } from "react";
import { Upload, FileText, Loader2, CheckCircle2, XCircle, Camera, Send, RefreshCw, ChevronRight, Sparkles, Printer } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import Markdown from "react-markdown";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import "katex/dist/katex.min.css";
import { analyzeWork } from "../services/gemini";

interface Problem {
  problem: string;
  answer: string;
}

interface WorksheetModeProps {
  problems: Problem[];
  onRestart: () => void;
}

export default function WorksheetMode({ problems, onRestart }: WorksheetModeProps) {
  const [currentIdx, setCurrentIdx] = useState(0);
  const [userAnswer, setUserAnswer] = useState("");
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [feedback, setFeedback] = useState<string | null>(null);
  const [isCorrect, setIsCorrect] = useState<boolean | null>(null);
  const [capturedImage, setCapturedImage] = useState<string | null>(null);
  const [isPrinting, setIsPrinting] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const currentProblem = problems[currentIdx];

  const handlePrint = () => {
    window.print();
  };

  if (isPrinting) {
    return (
      <div className="max-w-4xl mx-auto p-12 bg-white min-h-screen print:p-0">
        <div className="flex justify-between items-center mb-12 print:hidden">
          <h2 className="text-2xl font-bold">Printable Worksheet</h2>
          <div className="flex gap-4">
            <button
              onClick={() => setIsPrinting(false)}
              className="px-6 py-2 bg-zinc-100 text-zinc-600 rounded-xl font-bold hover:bg-zinc-200 transition-all"
            >
              Back to App
            </button>
            <button
              onClick={handlePrint}
              className="px-6 py-2 bg-indigo-600 text-white rounded-xl font-bold hover:bg-indigo-700 transition-all flex items-center gap-2"
            >
              <Printer className="w-5 h-5" />
              Print Now
            </button>
          </div>
        </div>

        <div className="space-y-12">
          <div className="border-b-2 border-zinc-900 pb-6">
            <h1 className="text-4xl font-black uppercase tracking-tighter mb-2">Worksheet</h1>
            <div className="flex justify-between text-sm font-mono text-zinc-500">
              <span>Name: __________________________</span>
              <span>Date: __________________________</span>
            </div>
          </div>

          {problems.map((p, i) => (
            <div key={i} className="space-y-4">
              <div className="flex gap-4">
                <span className="font-bold text-xl">{i + 1}.</span>
                <div className="text-lg leading-relaxed flex-1">
                  <Markdown remarkPlugins={[remarkMath]} rehypePlugins={[rehypeKatex]}>
                    {p.problem}
                  </Markdown>
                </div>
              </div>
              <div className="h-48 border-2 border-zinc-100 rounded-2xl border-dashed"></div>
            </div>
          ))}
        </div>

        <div className="mt-20 pt-12 border-t border-zinc-100 text-center text-xs text-zinc-400 print:hidden">
          Generated by Learn It AI
        </div>
      </div>
    );
  }

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      setCapturedImage(event.target?.result as string);
    };
    reader.readAsDataURL(file);
  };

  const handleSubmit = async () => {
    if (!userAnswer.trim() && !capturedImage) return;
    
    setIsAnalyzing(true);
    setFeedback(null);
    try {
      const result = await analyzeWork(
        currentProblem.problem,
        currentProblem.answer,
        userAnswer,
        capturedImage || undefined
      );
      
      setFeedback(result || "No feedback received.");
      
      // Simple heuristic for correctness if AI doesn't explicitly say
      const correctKeywords = ["congratulations", "correct", "well done", "exactly right"];
      const lowerResult = result?.toLowerCase() || "";
      const isActuallyCorrect = correctKeywords.some(kw => lowerResult.includes(kw));
      setIsCorrect(isActuallyCorrect);
      
    } catch (error) {
      console.error("Analysis error:", error);
      setFeedback("Sorry, I couldn't analyze your work right now.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const nextProblem = () => {
    if (currentIdx + 1 < problems.length) {
      setCurrentIdx(currentIdx + 1);
      setUserAnswer("");
      setFeedback(null);
      setIsCorrect(null);
      setCapturedImage(null);
    } else {
      alert("Worksheet completed! Great job.");
      onRestart();
    }
  };

  return (
    <div className="max-w-3xl mx-auto mt-8 px-6 pb-20">
      <div className="mb-8 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="px-3 py-1 bg-amber-100 text-amber-700 rounded-full text-xs font-bold uppercase tracking-wider">
            Problem {currentIdx + 1} of {problems.length}
          </span>
        </div>
        <div className="flex items-center gap-4">
          <button
            onClick={() => setIsPrinting(true)}
            className="p-2 text-zinc-400 hover:text-indigo-600 transition-colors"
            title="Switch to printable view"
          >
            <Printer className="w-5 h-5" />
          </button>
          <button 
            onClick={onRestart}
            className="text-sm text-zinc-400 hover:text-zinc-600 transition-colors"
          >
            Exit Worksheet
          </button>
        </div>
      </div>

      <motion.div
        key={currentIdx}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white rounded-3xl p-8 shadow-sm border border-zinc-100"
      >
        <div className="text-xl font-semibold text-zinc-800 mb-8 leading-relaxed">
          <Markdown remarkPlugins={[remarkMath]} rehypePlugins={[rehypeKatex]}>
            {currentProblem.problem}
          </Markdown>
        </div>

        <div className="space-y-6">
          <div className="relative">
            <textarea
              value={userAnswer}
              onChange={(e) => setUserAnswer(e.target.value)}
              placeholder="Type your solution or answer here..."
              className="w-full h-40 p-6 bg-zinc-50 border border-zinc-200 rounded-2xl focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-all text-zinc-700 resize-none"
            />
            
            <div className="absolute bottom-4 right-4 flex items-center gap-2">
              <input
                type="file"
                accept="image/*"
                className="hidden"
                ref={fileInputRef}
                onChange={handleImageUpload}
              />
              <button
                onClick={() => fileInputRef.current?.click()}
                className={`p-2 rounded-xl transition-all ${
                  capturedImage ? "bg-emerald-100 text-emerald-600" : "bg-white text-zinc-400 hover:text-indigo-600 shadow-sm border border-zinc-200"
                }`}
                title="Upload a photo of your work"
              >
                <Camera className="w-5 h-5" />
              </button>
            </div>
          </div>

          {capturedImage && (
            <div className="relative w-32 h-32 rounded-xl overflow-hidden border border-zinc-200 group">
              <img src={capturedImage} alt="Work" className="w-full h-full object-cover" />
              <button 
                onClick={() => setCapturedImage(null)}
                className="absolute top-1 right-1 p-1 bg-black/50 text-white rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
              >
                <XCircle className="w-4 h-4" />
              </button>
            </div>
          )}

          {!isCorrect && (
            <button
              onClick={handleSubmit}
              disabled={isAnalyzing || (!userAnswer.trim() && !capturedImage)}
              className="w-full py-4 bg-zinc-900 text-white rounded-2xl font-bold hover:bg-zinc-800 disabled:opacity-50 transition-all flex items-center justify-center gap-2"
            >
              {isAnalyzing ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Analyzing your work...
                </>
              ) : (
                <>
                  <Send className="w-5 h-5" />
                  Check My Work
                </>
              )}
            </button>
          )}
        </div>

        <AnimatePresence>
          {feedback && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              className="mt-8 pt-8 border-t border-zinc-100"
            >
              <div className={`p-6 rounded-2xl border ${
                isCorrect ? "bg-emerald-50 border-emerald-100" : "bg-zinc-50 border-zinc-100"
              }`}>
                <div className="flex items-center gap-2 mb-3">
                  {isCorrect ? (
                    <CheckCircle2 className="w-5 h-5 text-emerald-500" />
                  ) : (
                    <Sparkles className="w-5 h-5 text-indigo-500" />
                  )}
                  <span className={`font-bold text-sm ${isCorrect ? "text-emerald-700" : "text-zinc-900"}`}>
                    {isCorrect ? "Excellent!" : "AI Feedback"}
                  </span>
                </div>
                <div className="prose prose-sm max-w-none text-zinc-600">
                  <Markdown remarkPlugins={[remarkMath]} rehypePlugins={[rehypeKatex]}>
                    {feedback}
                  </Markdown>
                </div>
              </div>

              {isCorrect ? (
                <button
                  onClick={nextProblem}
                  className="w-full mt-6 py-4 bg-indigo-600 text-white rounded-2xl font-bold hover:bg-indigo-700 transition-all flex items-center justify-center gap-2"
                >
                  Next Problem
                  <ChevronRight className="w-5 h-5" />
                </button>
              ) : (
                <div className="mt-4 text-center">
                  <p className="text-xs text-zinc-400">
                    Try adjusting your answer above based on the feedback.
                  </p>
                </div>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </div>
  );
}
